# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://t.me/s/ssrv2taytgshare?before

# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://t.me/s/SSRlist?before

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ssrusb

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/trojan

# 订阅链接
- type: subscribe
  options:
    url: https://raw.fastgit.org/freefq/free/master/ssr

# 订阅链接“www.linbaoz.com”
- type: subscribe
  options:
    url: https://www.linbaoz.com/ss/sub

# 订阅链接“www.linbaoz.com”
- type: subscribe
  options:
    url: https://www.linbaoz.com/sip002/sub

# 订阅链接“www.linbaoz.com”
- type: subscribe
  options:
    url: https://www.linbaoz.com/ssr/sub

# 订阅链接“www.linbaoz.com”
- type: subscribe
  options:
    url: https://www.linbaoz.com/vmess/sub	

# 订阅链接“www.linbaoz.com”
- type: subscribe
  options:
    url: https://www.linbaoz.com/trojan/sub

# 订阅链接“sspool.herokuapp.com”
- type: subscribe
  options:
    url: https://sspool.herokuapp.com/ss/sub

# 订阅链接“sspool.herokuapp.com”
- type: subscribe
  options:
    url: https://sspool.herokuapp.com/sip002/sub

# 订阅链接“sspool.herokuapp.com”
- type: subscribe
  options:
    url: https://sspool.herokuapp.com/ssr/sub

# 订阅链接“sspool.herokuapp.com”
- type: subscribe
  options:
    url: https://sspool.herokuapp.com/vmess/sub

# 订阅链接“sspool.herokuapp.com”
- type: subscribe
  options:
    url: https://sspool.herokuapp.com/trojan/sub

# 订阅链接“www.daode.download”
- type: subscribe
  options:
    url: https://blog.daodewang.org/ss/sub

# 订阅链接“www.daode.download”
- type: subscribe
  options:
    url: https://blog.daodewang.org/sip002/sub

# 订阅链接“www.daode.download”
- type: subscribe
  options:
    url: https://blog.daodewang.org/ssr/sub

# 订阅链接“www.daode.download”
- type: subscribe
  options:
    url: https://blog.daodewang.org/vmess/sub

# 订阅链接“www.daode.download”
- type: subscribe
  options:
    url: https://blog.daodewang.org/trojan/sub

# 订阅链接“proxy.purel.in”
- type: subscribe
  options:
    url: https://proxy.purel.in/ss/sub

# 订阅链接“proxy.purel.in”
- type: subscribe
  options:
    url: https://proxy.purel.in/sip002/sub

# 订阅链接“proxy.purel.in”
- type: subscribe
  options:
    url: https://proxy.purel.in/ssr/sub

# 订阅链接“proxy.purel.in”
- type: subscribe
  options:
    url: https://proxy.purel.in/vmess/sub

# 订阅链接“proxy.purel.in”
- type: subscribe
  options:
    url: https://proxy.purel.in/trojan/sub

# 订阅链接“fu.stgod.com”
- type: subscribe
  options:
    url: https://hello.stgod.com/ss/sub

# 订阅链接“fu.stgod.com”
- type: subscribe
  options:
    url: https://hello.stgod.com/sip002/sub

# 订阅链接“fu.stgod.com”
- type: subscribe
  options:
    url: https://hello.stgod.com/ssr/sub

# 订阅链接“fu.stgod.com”
- type: subscribe
  options:
    url: https://hello.stgod.com/vmess/sub

# 订阅链接“fu.stgod.com”
- type: subscribe
  options:
    url: https://hello.stgod.com/trojan/sub

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://t.me/s/ssrv2taytgshare?before

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://t.me/s/SSRlist?before

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://raw.githubusercontent.com/freefq/free/master/README.md

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: ssList
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: V2List
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: freeshadowsock
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: baipiaojiedian
    num: 200

# tg频道抓取
- type: tgchannel
  options:
    channel: dafeiji100
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-2-1.html

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-36-1.html

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-50-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/Clash.yml
    
# 某个网站抓取
- type: web-freessrxyz
  options:
    url: https://free-ss.site

# 某个网站抓取
- type: web-freessrxyz
  options:
    url: https://t.me/s/ssrv2taytgshare?before

# 某个网站抓取
- type: web-freessrxyz
  options:
    url: https://t.me/s/SSRlist?before

# 某个网站抓取
- type: web-freessrxyz
  options:
    url: https://github.com/freefq/free

# 某个网站抓取
- type: web-freessrxyz
  options:
    url: https://www.freefq.com/free-ssr